version: '3'

services:
  core0:
    user: "0:0"
    container_name: core0
    image: ghcr.io/cosmos/gaia:v21.0.1
    ports:
      - "9090:9090"
      - "26657:26657"
    entrypoint: ["/bin/sh", "/opt/start_core0.sh"]
    # entrypoint: ["sleep", "infinity"]
    volumes:
      - ./gaia/core0/config/node_key.json:/opt/config/node_key.json:ro
      - ./gaia/core0/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ./gaia/core0/data/:/opt/data/
      - ./gaia/core0/keyring-test:/opt/keyring-test:ro
      - ./gaia/core0/config/config.toml:/opt/config/config.toml:ro
      - ./gaia/core0/config/app.toml:/opt/config/app.toml:ro
      - ./gaia/core0/config/genesis.json:/opt/config/genesis.json:rw
      - ./gaia/start_core0.sh:/opt/start_core0.sh:ro
    networks:
      gaia-networks:
        ipv4_address: 10.110.101.11

  core1:
    user: "0:0"
    container_name: core1
    image: ghcr.io/cosmos/gaia:v21.0.1
    depends_on:
      - core0
    entrypoint: ["/bin/sh", "/opt/start_core0.sh"]
    volumes:
      - ./gaia/core1/config/node_key.json:/opt/config/node_key.json:ro
      - ./gaia/core1/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ./gaia/core1/data/:/opt/data/
      - ./gaia/core1/keyring-test:/opt/keyring-test:ro
      - ./gaia/core1/config/config.toml:/opt/config/config.toml:ro
      - ./gaia/core1/config/app.toml:/opt/config/app.toml:ro
      - ./gaia/core0/config/genesis.json:/opt/config/genesis.json:rw
      - ./gaia/start_core0.sh:/opt/start_core0.sh:ro
    networks:
      gaia-networks:
        ipv4_address: 10.110.101.12


  core2:
    user: "0:0"
    container_name: core2
    image: ghcr.io/cosmos/gaia:v21.0.1
    depends_on:
      - core0
    entrypoint: ["/bin/sh", "/opt/start_core0.sh"]
    volumes:
      - ./gaia/core2/config/node_key.json:/opt/config/node_key.json:ro
      - ./gaia/core2/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ./gaia/core2/data/:/opt/data/
      - ./gaia/core2/keyring-test:/opt/keyring-test:ro
      - ./gaia/core2/config/config.toml:/opt/config/config.toml:ro
      - ./gaia/core2/config/app.toml:/opt/config/app.toml:ro
      - ./gaia/core0/config/genesis.json:/opt/config/genesis.json:rw
      - ./gaia/start_core0.sh:/opt/start_core0.sh:ro
    networks:
      gaia-networks:
        ipv4_address: 10.110.101.13
  
  core3:
    user: "0:0"
    container_name: core3
    image: ghcr.io/cosmos/gaia:v21.0.1
    depends_on:
      - core0
    entrypoint: ["/bin/sh", "/opt/start_core0.sh"]
    volumes:
      - ./gaia/core3/config/node_key.json:/opt/config/node_key.json:ro
      - ./gaia/core3/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ./gaia/core3/data/:/opt/data/
      - ./gaia/core3/keyring-test:/opt/keyring-test:ro
      - ./gaia/core3/config/config.toml:/opt/config/config.toml:ro
      - ./gaia/core3/config/app.toml:/opt/config/app.toml:ro
      - ./gaia/core0/config/genesis.json:/opt/config/genesis.json:rw
      - ./gaia/start_core0.sh:/opt/start_core0.sh:ro
    networks:
      gaia-networks:
        ipv4_address: 10.110.101.14


networks:
  gaia-networks:
    name: gaia-network
    driver: bridge
    ipam:
     config:
       - subnet: 10.110.0.0/16