services:
  core0:
    user: "0:0"
    container_name: core0
    image: axelarnet/axelar-core:v1.1.3
    platform: linux/amd64
    ports:
      - "9090:9090"
      - "26657:26657"
      - "13117:1317"
    entrypoint: ["/bin/sh", "/opt/start_core0.sh"]
    volumes:
      - ./core0/config/node_key.json:/opt/config/node_key.json
      - ./core0/config/priv_validator_key.json:/opt/config/priv_validator_key.json
      - ./core0/keyring-test:/opt/keyring-test
      - ./core0/config/config.toml:/opt/config/config.toml
      - ./core0/config/app.toml:/opt/config/app.toml
      - ./core0/config/genesis.json:/opt/config/genesis.json
      - ./start_core0.sh:/opt/start_core0.sh
    networks:
      axlear-networks:
        ipv4_address: 10.112.101.11

  core1:
    user: "0:0"
    container_name: core1
    image: axelarnet/axelar-core:v1.1.3
    platform: linux/amd64
    depends_on:
      - core0
    ports:
      - "13118:1317"
    entrypoint: ["/bin/sh", "/opt/start_core0.sh"]
    volumes:
      - ./core1/config/node_key.json:/opt/config/node_key.json
      - ./core1/config/priv_validator_key.json:/opt/config/priv_validator_key.json
      - ./core1/keyring-test:/opt/keyring-test
      - ./core1/config/config.toml:/opt/config/config.toml
      - ./core1/config/app.toml:/opt/config/app.toml
      - ./core0/config/genesis.json:/opt/config/genesis.json
      - ./start_core0.sh:/opt/start_core0.sh
    networks:
      axlear-networks:
        ipv4_address: 10.112.101.12

  core2:
    user: "0:0"
    container_name: core2
    image: axelarnet/axelar-core:v1.1.3
    platform: linux/amd64
    depends_on:
      - core0
    ports:
      - "13119:1317"
    entrypoint: ["/bin/sh", "/opt/start_core0.sh"]
    volumes:
      - ./core2/config/node_key.json:/opt/config/node_key.json
      - ./core2/config/priv_validator_key.json:/opt/config/priv_validator_key.json
      - ./core2/keyring-test:/opt/keyring-test
      - ./core2/config/config.toml:/opt/config/config.toml
      - ./core2/config/app.toml:/opt/config/app.toml
      - ./core0/config/genesis.json:/opt/config/genesis.json
      - ./start_core0.sh:/opt/start_core0.sh
    networks:
      axlear-networks:
        ipv4_address: 10.112.101.13

  core3:
    user: "0:0"
    container_name: core3
    image: axelarnet/axelar-core:v1.1.3
    platform: linux/amd64
    depends_on:
      - core0
    ports:
      - "13110:1317"
    entrypoint: ["/bin/sh", "/opt/start_core0.sh"]
    volumes:
      - ./core3/config/node_key.json:/opt/config/node_key.json
      - ./core3/config/priv_validator_key.json:/opt/config/priv_validator_key.json
      - ./core3/keyring-test:/opt/keyring-test
      - ./core3/config/config.toml:/opt/config/config.toml
      - ./core3/config/app.toml:/opt/config/app.toml
      - ./core0/config/genesis.json:/opt/config/genesis.json
      - ./start_core0.sh:/opt/start_core0.sh
    networks:
      axlear-networks:
        ipv4_address: 10.112.101.14

networks:
  axlear-networks:
    name: axlear-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.112.0.0/16
