services:
  core0:
    user: "0:0"
    container_name: core0
    image: ghcr.io/rollkit/local-celestia-devnet:latest
    environment:
      - MONIKER=core0
      - CELESTIA_HOME=/opt
      - AMOUNT=5000000000utia
    ports:
      - "9090:9090"
      - "26657:26657"
      - "13117:1317"
    entrypoint: ["/bin/bash", "/opt/start_core0.sh"]
    volumes:
      - ./core0/config/node_key.json:/opt/config/node_key.json
      - ./core0/config/priv_validator_key.json:/opt/config/priv_validator_key.json
      - ./core0/keyring-test:/opt/keyring-test
      - ./core0/config/config.toml:/opt/config/config.toml
      - ./core0/config/app.toml:/opt/config/app.toml
      - ./core0/config/genesis.json:/opt/config/genesis.json
      - ./start_core0.sh:/opt/start_core0.sh
    networks:
      celestia-networks:
        ipv4_address: 10.122.101.11

  core1:
    user: "0:0"
    container_name: core1
    image: ghcr.io/rollkit/local-celestia-devnet:latest
    depends_on:
      - core0
    environment:
      - MONIKER=core1
      - CELESTIA_HOME=/opt
      - AMOUNT=5000000000utia
    ports:
      - "26658:26657"
      - "13118:1317"
    entrypoint: ["/bin/bash", "/opt/start_core0.sh"]
    volumes:
      - ./core1/config/node_key.json:/opt/config/node_key.json
      - ./core1/config/priv_validator_key.json:/opt/config/priv_validator_key.json
      - ./core1/keyring-test:/opt/keyring-test
      - ./core1/config/config.toml:/opt/config/config.toml
      - ./core1/config/app.toml:/opt/config/app.toml
      - ./core0/config/genesis.json:/opt/config/genesis.json
      - ./start_core0.sh:/opt/start_core0.sh
    networks:
      celestia-networks:
        ipv4_address: 10.122.101.12

  core2:
    user: "0:0"
    container_name: core2
    image: ghcr.io/rollkit/local-celestia-devnet:latest
    depends_on:
      - core0
    environment:
      - MONIKER=core2
      - CELESTIA_HOME=/opt
      - AMOUNT=5000000000utia
    ports:
      - "26659:26657"
      - "13119:1317"
    entrypoint: ["/bin/bash", "/opt/start_core0.sh"]
    volumes:
      - ./core2/config/node_key.json:/opt/config/node_key.json
      - ./core2/config/priv_validator_key.json:/opt/config/priv_validator_key.json
      - ./core2/keyring-test:/opt/keyring-test
      - ./core2/config/config.toml:/opt/config/config.toml
      - ./core2/config/app.toml:/opt/config/app.toml
      - ./core0/config/genesis.json:/opt/config/genesis.json
      - ./start_core0.sh:/opt/start_core0.sh
    networks:
      celestia-networks:
        ipv4_address: 10.122.101.13

  core3:
    user: "0:0"
    container_name: core3
    image: ghcr.io/rollkit/local-celestia-devnet:latest
    depends_on:
      - core0
    environment:
      - MONIKER=core3
      - CELESTIA_HOME=/opt
      - AMOUNT=5000000000utia
    ports:
      - "26660:26657"
      - "13110:1317"
    entrypoint: ["/bin/bash", "/opt/start_core0.sh"]
    volumes:
      - ./core3/config/node_key.json:/opt/config/node_key.json
      - ./core3/config/priv_validator_key.json:/opt/config/priv_validator_key.json
      - ./core3/keyring-test:/opt/keyring-test
      - ./core3/config/config.toml:/opt/config/config.toml
      - ./core3/config/app.toml:/opt/config/app.toml
      - ./core0/config/genesis.json:/opt/config/genesis.json
      - ./start_core0.sh:/opt/start_core0.sh
    networks:
      celestia-networks:
        ipv4_address: 10.122.101.14

networks:
  celestia-networks:
    name: celestia-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.122.0.0/16
