services:
  core0:
    user: "0:0"
    container_name: core0
    image: ghcr.io/rollkit/local-celestia-devnet:latest
    environment:
      - MONIKER=core0
      - CELESTIA_HOME=/opt
      - AMOUNT=5000000000utia
    ports:
      - "9090:9090"
      - "26657:26657"
    entrypoint: ["/bin/bash", "/opt/start_core0.sh"]
    volumes:
      - ./core0/config/node_key.json:/opt/config/node_key.json
      - ./core0/config/priv_validator_key.json:/opt/config/priv_validator_key.json
      - ./core0/keyring-test:/opt/keyring-test
      - ./config.toml:/opt/config/config.toml
      - ./app.toml:/opt/config/app.toml
      - ./genesis.json:/opt/config/genesis.json
      - ./start_core0.sh:/opt/start_core0.sh

  core1:
    user: "0:0"
    container_name: core1
    image: ghcr.io/rollkit/local-celestia-devnet:latest
    depends_on:
      - core0
    environment:
      - MONIKER=core1
      - CELESTIA_HOME=/opt
      - AMOUNT=5000000000utia
    entrypoint: ["/bin/bash", "/opt/start_node.sh"]
    volumes:
      - ./core1/config/node_key.json:/opt/config/node_key.json
      - ./core1/config/priv_validator_key.json:/opt/config/priv_validator_key.json
      - ./core1/keyring-test:/opt/keyring-test
      - ./config.toml:/opt/config/config.toml
      - ./app.toml:/opt/config/app.toml
      - ./genesis.json:/opt/config/genesis.json
      - ./start_node.sh:/opt/start_node.sh

  core2:
    user: "0:0"
    container_name: core2
    image: ghcr.io/rollkit/local-celestia-devnet:latest
    depends_on:
      - core0
    environment:
      - MONIKER=core2
      - CELESTIA_HOME=/opt
      - AMOUNT=5000000000utia
    entrypoint: ["/bin/bash", "/opt/start_node.sh"]
    volumes:
      - ./core2/config/node_key.json:/opt/config/node_key.json
      - ./core2/config/priv_validator_key.json:/opt/config/priv_validator_key.json
      - ./core2/keyring-test:/opt/keyring-test
      - ./config.toml:/opt/config/config.toml
      - ./app.toml:/opt/config/app.toml
      - ./genesis.json:/opt/config/genesis.json
      - ./start_node.sh:/opt/start_node.sh

  core3:
    user: "0:0"
    container_name: core3
    image: ghcr.io/rollkit/local-celestia-devnet:latest
    depends_on:
      - core0
    environment:
      - MONIKER=core3
      - CELESTIA_HOME=/opt
      - AMOUNT=5000000000utia
    entrypoint: ["/bin/bash", "/opt/start_node.sh"]
    volumes:
      - ./core3/config/node_key.json:/opt/config/node_key.json
      - ./core3/config/priv_validator_key.json:/opt/config/priv_validator_key.json
      - ./core3/keyring-test:/opt/keyring-test
      - ./config.toml:/opt/config/config.toml
      - ./app.toml:/opt/config/app.toml
      - ./genesis.json:/opt/config/genesis.json
      - ./start_node.sh:/opt/start_node.sh
