services:
  core0:
    user: "0:0"
    container_name: core0
    image: ghcr.io/rollkit/local-celestia-devnet:latest
    ports:
      - "9090:9090"
      - "26657:26657"
    command: ["/bin/bash", "/opt/start_core0.sh"]
    volumes:
      - ./celestia/core0/config/node_key.json:/opt/config/node_key.json:ro
      - ./celestia/core0/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ./celestia/core0/keyring-test:/opt/keyring-test:ro
      - ./celestia/config.toml:/opt/config/config.toml:ro
      - ./celestia/app.toml:/opt/config/app.toml:ro
      - ./celestia/genesis.json:/opt/config/genesis.json:rw
      - ./celestia/start_core0.sh:/opt/start_core0.sh:ro

  core1:
    user: "0:0"
    container_name: core1
    image: ghcr.io/rollkit/local-celestia-devnet:latest
    depends_on:
      - core0
    environment:
      - MONIKER=core1
      - CELESTIA_HOME=/opt
      - AMOUNT=5000000000utia
    command: ["/bin/bash", "/opt/start_core0.sh"]
    volumes:
      - ./celestia/core1/config/node_key.json:/opt/config/node_key.json:ro
      - ./celestia/core1/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ./celestia/core1/keyring-test:/opt/keyring-test:ro
      - ./celestia/config.toml:/opt/config/config.toml:ro
      - ./celestia/app.toml:/opt/config/app.toml:ro
      - ./celestia/genesis.json:/opt/config/genesis.json:rw
      - ./celestia/start_node_and_create_validator.sh:/opt/start_node_and_create_validator.sh:ro


  core2:
    user: "0:0"
    container_name: core2
    image: ghcr.io/rollkit/local-celestia-devnet:latest
    depends_on:
      - core0
    environment:
      - MONIKER=core2
      - CELESTIA_HOME=/opt
      - AMOUNT=5000000000utia
    command: ["/bin/bash", "/opt/start_core0.sh"]
    volumes:
      - ./celestia/core2/config/node_key.json:/opt/config/node_key.json:ro
      - ./celestia/core2/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ./celestia/core2/keyring-test:/opt/keyring-test:ro
      - ./celestia/config.toml:/opt/config/config.toml:ro
      - ./celestia/app.toml:/opt/config/app.toml:ro
      - ./celestia/genesis.json:/opt/config/genesis.json:rw
      - ./celestia/start_node_and_create_validator.sh:/opt/start_node_and_create_validator.sh:ro
  
  core3:
    user: "0:0"
    container_name: core3
    image: ghcr.io/rollkit/local-celestia-devnet:latest
    depends_on:
      - core0
    environment:
      - MONIKER=core3
      - CELESTIA_HOME=/opt
      - AMOUNT=5000000000utia
    command: ["/bin/bash", "/opt/start_core0.sh"]
    volumes:
      - ./celestia/core3/config/node_key.json:/opt/config/node_key.json:ro
      - ./celestia/core3/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ./celestia/core3/keyring-test:/opt/keyring-test:ro
      - ./celestia/config.toml:/opt/config/config.toml:ro
      - ./celestia/app.toml:/opt/config/app.toml:ro
      - ./celestia/genesis.json:/opt/config/genesis.json:rw
      - ./celestia/start_node_and_create_validator.sh:/opt/start_node_and_create_validator.sh:ro